Fix git-tree for non-yadm repos, add cloc-git and styler

diff --git a/git-tree b/git-tree
--- a/git-tree
+++ b/git-tree
@@ -3,19 +3,25 @@
 # Prints out tree of yadm/git tracked files
 
 help() {
+    self_name=$(basename "$0")
     if [ -n "$1" ]; then
         >&2 echo
-        >&2 echo "$(basename "$0") -- Prints tree of files tracked with yadm/git"
-        >&2 echo "usage: [--root tree_root_name] <tree command options>"
+        >&2 echo "$self_name -- Prints tree of files tracked with yadm/git"
+        >&2 echo "usage: $self_name [--root tree_root_name] <tree command options>"
         exit 1
     else
-        echo "$(basename "$0") -- Prints tree of files tracked with yadm/git"
-        echo "usage: [--root tree_root_name] <tree command options>"
+        echo "$self_name -- Prints tree of files tracked with yadm/git"
+        echo "usage: $self_name [--root tree_root_name] <tree command options>"
         exit 0
     fi
 }
 
-command -v tree 1> /dev/null || { echo "Please install tree and try again"; exit 1; }
+require() {
+    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed";exit 1; }
+}
+
+require git
+require tree
 
 PARAMS=()
 while (( "$#" )); do
@@ -25,10 +31,10 @@ while (( "$#" )); do
     *) PARAMS+=("$1");shift;;
   esac
 done
-eval set -- "${PARAMS[@]}"
+set -- "${PARAMS[@]}"
 
-out=$(eval "$(command -v yadm || command -v git)" ls-files | tree --fromfile "${PARAMS[@]}") || help 'err'
-if [[ -n $ROOT ]]; then
-    out=$(sed "1s/.*/$ROOT/" <<< "$out")
+out="$(eval "$([[ -d "${PWD}/.git" ]] && command -v git || command -v yadm)" ls-files | tree --fromfile "${PARAMS[@]}")" || help 'err'
+if [[ -n "$ROOT" ]]; then
+    out="$(sed "1s/.*/$ROOT/" <<< "$out")"
 fi
 printf %s "$out"
