Add active-window-pid script

diff --git a/pwd-launch b/pwd-launch
--- a/pwd-launch
+++ b/pwd-launch
@@ -3,26 +3,28 @@
 # Finds and appends pwd of currently focused window using EWMH to the given command
 
 ARGS=("$@")
-cmd_exists() {
-    command -v "$1" 1> /dev/null
-}
 fallback() {
     exec "${ARGS[@]}"
 }
+require_or_fallback() {
+    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed"; fallback; }
+}
 
-cmd_exists xprop || fallback
-cmd_exists pgrep || fallback
-cmd_exists readlink || fallback
+require_or_fallback pgrep
+require_or_fallback readlink
 
-wid=$(xprop -root -f _NET_ACTIVE_WINDOW 0x ' $0\n' _NET_ACTIVE_WINDOW | cut -d ' ' -f 2)
-[[ $wid -ne '0x0' ]] || fallback
+pid_script="${0%/*}/active-window-pid"
+[[ -x "$pid_script" ]] || fallback
+pid=$($pid_script) || fallback
 
-pid=$(xprop -root -f _NET_WM_PID 0c ' $0\n' -id $wid _NET_WM_PID | cut -d ' ' -f 2)
 child_pid="$pid"
 child_procs=$(pgrep -P "$pid")
 if [[ $(wc -l <<< "$child_procs") -eq 1 ]]; then
     child_pid="$child_procs"
 fi
 
+[[ -z "$child_pid" ]] && fallback
+
 child_pwd=$(readlink -f "/proc/$child_pid/cwd") || fallback
+
 exec "$@" "$child_pwd"
